apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pillowfight
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pillowfight
            image: sequoiatools/pillowfight:v5.0.1
            command: ["cbc-pillowfight",
                      "-U", "couchbase://cb-example-0000.cb-example.default.svc/default?select_bucket=true",
                      "-I", "100000", "-B", "250", "-c", "400", "-t", "1", "-P", "password"]
          restartPolicy: Never